<?php
return [
    'SALT_KEY' => 'melobridge',
    'ENC_KEY' => 'melobridge',
    'StatusCodeText' => [
        '01' => 'Delivered',
        '02' => 'Notice Left(Subset below)',
        '53' => 'Notice Left (Receptacle Blocked)',
        '54' => 'Notice Left (Receptacle Full/Item Oversized)',
        '55' => 'Notice Left (No Secure Location Available)',
        '56' => 'Notice Left (No Authorized Recipient Available)',
        '07' => 'Arrival at Unit',
        '08' => 'Arrived at USPS Facility',
        '10' => 'Arrived at USPS Facility or Departed USPS Facility',
        '51' => 'Delivery Attempted - No Access to Delivery Location',
        '52' => 'Held at Post Office, At Customer Request',
        '57' => 'Delivery Exception, Local Weather Delay',
        '58' => 'Held at Post Office, At Customer Request',
        '59' => 'Out for Delivery Out for Redelivery',
        '60' => 'Delivered to Agent for Final Delivery',
        '43' => 'Delivered',
        '71' => 'Rescheduled to Next Delivery Day',
        '72' => 'Delivery Exception, Animal Interference',
        'A1' => 'Arrived at USPS Facility',
        'AD' => 'Accepted at USPS Destination Sort Facility',
        'AE' => 'Arrived USPS Facility',
        'B5' => 'Received by U.S. Postal Service from U.S. Customs',
        'DE' => 'Arrived at USPS Facility or Departed USPS Facility',
        'E1' => 'Departed USPS Facility',
        'EF' => 'Departed USPS Facility',
        'L1' => 'Departed USPS Facility',
        'OF' => 'Out for Delivery',
        'WX' => 'Processing Exception, Regional Weather Delay',
        '63' => 'Delivered to Recipient by Agent',
        '64' => 'Undeliverable to Recipient by Agent',
        '80' => 'Picked Up By Shipping Partner, USPS Awaiting Item',
        '81' => 'Arrived Shipping Partner Facility, USPS Awaiting Item',
        '82' => 'Departed Shipping Partner Facility, USPS Awaiting Item',
        '86' => 'Delivered by Agent to Merchant',
        '87' => 'Final Disposition by Agent'
    ],
    'company_name'=>'Mello Bridge',
    'purcel_from_address_line1'=>'701 Harrison Ave',
    'purcel_from_city'=>'Blaine',
    'purcel_from_state_province'=>'WA',
    'purcel_from_postal_code'=>'98230',
];
?>
